[package]
name = "rtq"
version = "0.1.0"
authors = ["l_hou"]

[lib]
name = "rtqlib"
path = "src/lib.rs"

[dependencies]
clap = "2.31.2"
chrono = "0.4.2"
glob = "0.2.11"
libc = "0.2"
rusqlite = "0.13.0"
serde = "1.0.66"
serde_json = "1.0.20"
serde_derive = "1.0.66"
simplelog = "0.5.0"
log = "0.4.2"
